name: ACEest CI/CD → Local Jenkins

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          pip install -r requirements.txt pytest flake8
          flake8 . && pytest
      - run: docker build -t aceest-app:${{ github.sha }} .

  trigger-local-jenkins:
    if: github.ref_type == 'tag'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Local Jenkins
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
          VERSION: ${{ github.ref_name }}
        run: |
          echo "Getting Jenkins crumb..."

          CRUMB=$(curl -s \
            --user "$JENKINS_USER:$JENKINS_TOKEN" \
            "$JENKINS_URL/crumbIssuer/api/json" \
            | python -c "import sys, json; print(json.load(sys.stdin)['crumb'])")

          echo "Triggering Jenkins build..."

          curl -X POST \
            "$JENKINS_URL/job/ACEest-Build/buildWithParameters?VERSION=$VERSION" \
            --user "$JENKINS_USER:$JENKINS_TOKEN" \
            -H "Jenkins-Crumb:$CRUMB"
